baseURL = 'https://me.dblsoft.xyz/'
languageCode = 'pt-BR'
title = 'Mauricio Junio'
theme = 'ananke'

[permalinks]
  [permalinks.page]
    posts = '/blog/:slugorcontentbasename/'
  [permalinks.section]
    posts = '/blog/'

[caches]
  [caches.images]
    dir = ':cacheDir/images'